spring:
  cloud:
    function:
      definition: testConsumer
    stream:
      bindings:
        testTopic-out-0:
          destination: test
          group: local
        testConsumer-in-0:
          destination: test
          group: local
      kafka:
        binder:
          auto-create-topics: false
          auto-add-partitions: false
          auto-alter-topics: true
          brokers: mbp.lan:9092

