server:
  port: 9900
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 5KB

spring:
  threads:
    virtual:
      enabled: true

  application:
    name: pcc-puppet-enforcer-fuimos
  main:
    web-application-type: servlet

  cloud:
    vault:
      kv:
        application-name: ${spring.application.name},global
      config:
        lifecycle:
          enabled: true
          min-renewal: 1m
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${provider-keycloak-url}/realms/${keycloak-realm}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${provider-keycloak-url}/realms/${keycloak-realm}
          jwk-set-uri: ${provider-keycloak-url}/realms/${keycloak-realm}/protocol/openid-connect/certs

logging:
  pattern:
    console: "[${spring.application.name}] [%t] [%-5p] [%X{traceId}] [%X{spanId}] [%X{track-id}] [%logger{15}] [%m]%n"
  level:
    org.springframework.boot.web: DEBUG
    reactor.netty.http.client: INFO
    io.micrometer: INFO
    pcc: DEBUG

management:
  tracing:
    baggage:
      correlation:
        enabled: true
        fields:
          - track-id
      remote-fields:
        - track-id
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: ${otlp-host-http}/v1/traces
      headers:
        track-id: track-id
        X-Org-Id: X-Org-Id
        X-Dept-Id: X-Dept-Id
        X-Member-Id: X-Member-Id
    metrics:
      export:
        enabled: true
        url: ${otlp-host-http}/v1/metrics

provider:
  keycloak:
    adminClientId: ${keycloak-admin-clientId}
    clientId: ${keycloak-clientId}
    clientSecret: ${keycloak-clientSecret}
    realm: ${keycloak-realm}