spring:
  http:
    services:
      operator-ingress:
        url: http://localhost:9900
        path: /operator
  data:
    mongodb:
      auto-index-creation: true
      uri: ${mongo-uri}
  cloud:
    stream:
      bindings:
        testTopic-out-0:
          destination: test
          group: local
      kafka:
        binder:
          auto-create-topics: false
          auto-add-partitions: false
          auto-alter-topics: true
          brokers: mbp.lan:9092

